### PR TITLE
fix(nix): pin rustc via rust-overlay so the Cachix build tracks stable

### PR DESCRIPTION
**Pull request by njbrake**
## Description

The **Push to Cachix** workflow has failed on every `main` push since #2129 bumped `rusqlite` 0.39 -> 0.40, which pulled in `libsqlite3-sys 0.38.1`. That crate's `build.rs:110` uses the `cfg_select!` macro, which is stable only in rustc >= 1.93. The flake builds with crane on nixpkgs' default rustc (currently **1.92.0**, nixpkgs input pinned 2026-02-17), so the build fails:

```
error[E0658]: use of unstable library feature `cfg_select`
  --> .../libsqlite3-sys-0.38.1/build.rs:110:9
```

Regular `CI` and `Tests` are unaffected because rustup `stable` on the runners is already 1.93+. Only the nix build was pinned to the lagging nixpkgs toolchain. Clean bisect: the last green Cachix run was the commit immediately before #2129; every run since fails with the identical error on both `ubuntu-latest` and `macos-latest`.

### Fix

Add the `oxalica/rust-overlay` input and pin the nix toolchain to latest stable via `craneLib.overrideToolchain`, decoupling it from whatever rustc the pinned nixpkgs happens to ship. This keeps the nix build in step with the rustup-stable the rest of CI uses, and prevents recurrence the next time a dependency's build script adopts a freshly-stabilized language feature. Using `stable.latest` (rather than a hard version) stays fully reproducible through the rust-overlay lock while avoiding becoming the next lagging pin.

### Verification

Installed nix locally and evaluated the flake: `aoe-with-web` resolves clean (overlay + `rust-bin` + `overrideToolchain` all wire up), and the pinned toolchain resolves to **rustc 1.96.0**, well above the 1.93 `cfg_select` floor. Full compile is gated by the Cachix workflow itself (its `paths` filter includes `flake.nix` + `flake.lock`, so it re-runs on this change).

## PR Type

- [ ] New Feature
- [ ] Bug Fix
- [ ] Refactor
- [ ] Documentation
- [x] Infrastructure / CI

## Checklist

- [x] New and existing tests pass
- [x] Documentation was updated where necessary
- [ ] For UI changes: included screenshot or recording

## Test Coverage Analysis

**Web dashboard / structured view (Playwright user story)**
- [x] N/A: this PR doesn't change a user-facing dashboard flow

**TUI / CLI (e2e test)**
- [x] N/A: this PR doesn't change TUI rendering, a CLI subcommand, or session lifecycle. This is a nix toolchain fix; the regression gate is the Cachix workflow re-running on the flake change.

## AI Usage

- [x] AI was used

**AI Model/Tool used:** Claude Code (Opus 4.8)

**Any Additional AI Details you'd like to share:** Claude diagnosed the regression (bisect + root cause), wrote the flake change, and verified it locally by evaluating the flake and resolving the pinned rustc version. @njbrake reviewed the diagnosis and fix.

- [x] I am an AI Agent filling out this form (check box if true)

---
<a href="https://app.blacksmith.sh/agent-of-empires/codesmith/agent-of-empires/pr/2181"><picture><source media="(prefers-color-scheme: dark)" srcset="https://pr-comments-assets.blacksmith.sh/codesmith/view-with-codesmith-dark-v2.svg"><source media="(prefers-color-scheme: light)" srcset="https://pr-comments-assets.blacksmith.sh/codesmith/view-with-codesmith-light-v2.svg">View with Codesmith</picture></a> <a href="https://backend.blacksmith.sh/track/enable-autofix?expires=1784143289&installation_id=139138837&pr_number=2181&repository=agent-of-empires%2Fagent-of-empires&return_to=https%3A%2F%2Fgithub.com%2Fagent-of-empires%2Fagent-of-empires%2Fpull%2F2181&signature=19c5e49e2eed689568b69b61fdc0f08de591cd7210f5eb2a0e6ec846e7afc801"><picture><source media="(prefers-color-scheme: dark)" srcset="https://pr-comments-assets.blacksmith.sh/codesmith/autofix-with-codesmith-dark.svg"><source media="(prefers-color-scheme: light)" srcset="https://pr-comments-assets.blacksmith.sh/codesmith/autofix-with-codesmith-light.svg">Autofix with Codesmith</picture></a>
<sup>Need help on this PR? Tag <code>/codesmith</code> with what you need. Autofix is disabled.</sup>

## What Changed

**flake.nix** was updated to fix a Cachix build failure by ensuring the nix build uses a compatible Rust version.

### Added
- New `rust-overlay` input from `oxalica/rust-overlay` to provide access to different Rust toolchain versions
- Rust toolchain pinning to the latest stable version (`pkgs.rust-bin.stable.latest.default`)
- Toolchain override for the crane library build system

### Removed
- Direct `pkgs` parameter from the `perSystem` function signature

### Modified
- `craneLib` initialization now uses the pinned stable Rust toolchain instead of inheriting whatever version is in the default nixpkgs

## Benefits

This fix resolves the Cachix build failures that have been occurring since the `rusqlite` dependency was bumped to version 0.40 in PR `#2129`. By decoupling the nix build environment from the rustc version shipped with the pinned nixpkgs, the build now uses Rust 1.96.0, which fully supports the `cfg_select!` macro required by the newer dependencies. This keeps the nix build synchronized with the stable Rust toolchain used in other CI workflows, preventing similar issues when future dependencies adopt newly-stabilized language features.

## Technical Details

The underlying issue: `libsqlite3-sys` 0.38.1 (introduced in the rusqlite 0.40 update) uses the `cfg_select!` macro, which only became stable in rustc 1.93. The nix build was using rustc 1.92.0 from the pinned nixpkgs (dated 2026-02-17), while other CI workflows with rustup were already running 1.93+. 

The solution uses the `oxalica/rust-overlay` to pin the toolchain to `stable.latest`, maintaining reproducibility through the rust-overlay lock while avoiding hard-coded version numbers that could become outdated.

### CODE REVIEW

**Comment by jerome-benoit** [comment]
It's not really representative of nix usage: users building from github repo are for sure using nixpkgs unstable and expect the repo to build from it instead of requiring to install a different rust toolchain in the build sandbox than the one in nixpkgs unstable. 

Changing the toolchain for nix just to silent a harmless error does not seem to worth it.
