### ISSUE TITLE
fix(web): useTerminal.ts broken after @xterm -> @wterm migration in #728

### ISSUE THREAD

**Issue by gdw2vs** [njbrake/agent-of-empires#731]
## Description

PR #728 replaced `@xterm/xterm` and `@xterm/addon-fit` with `@wterm/dom` and `@wterm/react` in `package.json`, but `useTerminal.ts` still imports from the old packages:

```ts
import { Terminal } from "@xterm/xterm";
import { FitAddon } from "@xterm/addon-fit";
```

This causes the build to fail immediately:

```
src/hooks/useTerminal.ts(2,26): error TS2307: Cannot find module '@xterm/xterm'
src/hooks/useTerminal.ts(3,26): error TS2307: Cannot find module '@xterm/addon-fit'
```

Two additional errors also surfaced from the same PR:

```
src/components/RightPanel.tsx(51,68): error TS2339: Property 'ctrlActiveRef' does not exist
src/components/RightPanel.tsx(51,83): error TS2339: Property 'clearCtrlRef' does not exist
src/components/TerminalView.tsx(21,68): error TS2339: Property 'ctrlActiveRef' does not exist
src/components/TerminalView.tsx(21,83): error TS2339: Property 'clearCtrlRef' does not exist
```

`TerminalView` and `RightPanel` destructure `ctrlActiveRef` and `clearCtrlRef` from `useTerminal`, but these refs were never added to its return value.

## Steps to reproduce

```
cd web && npm install && npm run build
```

## Fix

`useTerminal.ts` needs to be updated to use the `@wterm` API, and `ctrlActiveRef`/`clearCtrlRef` need to be created and returned from the hook.

**Comment by gdw2vs** [comment]
feel free to close.  It looks like CI caught the regression and you're probably aware...

**Comment by njbrake** [comment]
Fixed — the imports were updated to @wterm/dom and ctrlActiveRef/clearCtrlRef are wired up in #728's final state. Thanks for the report!
