### PR TITLE
fix(recovery): propagate on_launch hook timeouts as Status::Error

### LINKED ISSUE #1889: recovery: propagate on_launch hook timeout as cascade Err to mark Status::Error
## Background

PR #1872 (closes #1265) bounds `on_launch` hook execution during startup recovery with a per-thread `HookTimeoutScope` deadline; on expiry the child process tree is killed via `crate::process::kill_process_tree`, releasing the cross-process recovery lock. The fix preserves the pre-existing hook-error contract: `repo_config::run_hooks_captured` returns an `Err`, which `build_host_command` swallows via the existing warn-log-and-continue path at [`src/session/instance.rs#L1893-L1899`](https://github.com/agent-of-empires/agent-of-empires/blob/main/src/session/instance.rs#L1893-L1899). The cascade then proceeds and the agent launches with whatever partial setup the killed hook produced.

This was the smallest correct change (zero regression on `perform_recovery` happy path) but does not honor the literal test plan in #1265:

> "spawn a fake Instance whose on_launch is `sleep 60`; assert that the cascade returns `Err(HookTimeout)` within `HOOK_TIMEOUT + 1s`"

The implemented behavior is conservative: cascade succeeds, lock releases, and the user sees a session running with a possibly-broken setup rather than a `Status::Error` chip flagging the hook failure.

## Goal

Differentiate timeout errors from generic hook errors and propagate them up the recovery cascade so the offending instance ends up in `Status::Error` with a `last_error` mentioning the timed-out command, instead of silently launching a degraded session.

## Acceptance criteria

- A typed error variant (or downcast tag) lets `build_host_command` and `build_launch_command` distinguish "hook timed out" from "hook exited non-zero" or "hook spawn failed".
- On the recovery path only, timeouts propagate up through `start_with_size_opts` → `start_with_resume_fallback` → `restart_with_size_opts` → `run_recovery_for_instance`, returning `Err`.
- The recovery worker translates that `Err` into `Status::Error` with a `last_error` of the form `"on_launch hook timed out after 30s: <cmd>"`.
- Non-recovery paths (`aoe add`, manual restart) keep the current warn-log-and-continue behavior so user-initiated launches with slow hooks are not broken.
- Existing happy-path tests in `tests/integration/recovery_hook_timeout.rs` and the `aoe add` flow stay green.
- New test: pre-existing `Instance` with `on_launch = ["sleep 60"]`, recovery cascade, asserts the post-cascade `Status` is `Error` and `last_error` contains "timed out".

## Scope

- `src/session/repo_config.rs`: typed timeout error from `run_hook_with_timeout`.
- `src/session/instance.rs`: recovery-aware swallow vs. propagate at `build_host_command` and `build_launch_command`.
- `src/session/recovery.rs`: translate the `Err` into `Status::Error`.

## Out of scope

- Structured-view-mode hooks (handled by `cockpit_reconciler`).
- TUI on-create-hook timeout (`aoe add` flow).
- Changes to the `HookTimeoutScope` mechanism itself.

## References

- PR #1872 (the deadlock fix that deferred this).
- Issue #1265 acceptance test plan (third bullet under "Testing").

---

This issue body was drafted with AI assistance after PR #1872 shipped; the analysis reflects the conservative design choice (D4-CONSERVATIVE) made during PR #1872 and the #1265 test plan that the conservative path did not implement.

### PR DESCRIPTION
**Pull request by jerome-benoit**
## Description

Fixes #1889.

This PR makes recovery-only `on_launch` hook timeouts propagate as typed cascade errors so the affected instance is marked `Status::Error` instead of continuing with partial hook side effects while looking healthy.

What changed:

- Adds a typed `HookTimeout` error in `repo_config` and returns it when hook execution exceeds the active `HookTimeoutScope` deadline.
- Propagates typed hook timeouts through `build_host_command` / `build_launch_command`, while preserving warn-and-continue behavior for ordinary hook failures.
- Centralizes recovery cascade error translation in `run_recovery_for_instance`, stamping `Status::Error`, `last_error`, and `last_error_check` for both daemon and TUI recovery consumers.
- Simplifies the daemon worker by removing its inline cascade-error wrapping now that recovery owns the translation.
- Formats timeout recovery errors as `on_launch hook timed out after Ns: <cmd>` and walks the full anyhow chain so future context wrapping does not break detection.
- Follow-up review fixes add a direct stamp glue test, make the typed timeout assertion nonzero, use the same chain-walk detection style at both swallow sites, clarify the `HookTimeout` production invariant, and document the startup-recovery exception in the repo-config guide.

The non-recovery paths remain unchanged because production code does not install a `HookTimeoutScope` there, so `HookTimeout` is not constructible on those paths.

## PR Type

- [ ] New Feature
- [x] Bug Fix
- [ ] Refactor
- [ ] Documentation
- [ ] Infrastructure / CI

## Checklist

- [ ] New and existing tests pass
- [x] Documentation was updated where necessary
- [ ] For UI changes: included screenshot or recording

## Test Coverage Analysis

**Web dashboard / structured view (Playwright user story)**
- [x] N/A: this PR doesn't change a user-facing dashboard flow
- [ ] Added or updated a Playwright spec under `web/tests/` and updated `web/tests/coverage-matrix.json`
- [ ] Skipped a test, because: 

**TUI / CLI (e2e test)**
- [ ] N/A: this PR doesn't change TUI rendering, a CLI subcommand, or session lifecycle
- [ ] Added or updated an e2e test under `tests/e2e/`
- [x] Skipped a test, because: the changed behavior is covered by targeted recovery integration tests and recovery unit tests. This does change session lifecycle state, but the regression surface is the recovery cascade error path rather than a TUI rendering or CLI command-flow interaction.

Testing performed:

- `cargo fmt`
- `cargo fmt -- --check`
- `cargo clippy --all-targets --features serve -- -D warnings`, passed before the branch was updated with newer main commits.
- `cargo test --features serve`, before the branch update:
  - Result: 3964 passed, 3 failed.
  - The 3 failures were checked against `main` and are pre-existing or flaky:
    - `session::instance::tests::update_status_reconciles_running_hook_to_waiting_on_claude_approval_prompt`, fails on `main`.
    - `tmux::session::tests::capture_pane_with_cursor_returns_content_and_cursor`, fails on `main`.
    - `tmux::session::tests::test_is_pane_running_shell_targets_first_window_with_multiple_windows`, passed in isolation and appears flaky.
- Targeted recovery checks before the branch update, and again before pushing the follow-up commits:
  - `cargo test --test integration recovery_hook_timeout -- --nocapture`, 8 passed.
  - `cargo test --features serve --lib session::recovery::tests:: -- --nocapture`, 14 passed.
  - `cargo test --features serve --lib session::instance::tests::test_build_host_command -- --nocapture`, 6 passed.
- LSP diagnostics on modified Rust files: clean.

Current local caveat:

- After rebasing these follow-up commits onto the remote PR branch, which had already merged newer `main`, local Rust builds on this machine stop before AoE code at `libsqlite3-sys v0.38.1` with `error[E0658]: use of unstable library feature cfg_select` in the dependency build script. That comes from the upstream `rusqlite 0.40.0` dependency bump now present on the updated base, not from this PR's recovery diff.

## AI Usage

- [ ] No AI was used
- [x] AI was used

**AI Model/Tool used:**

Sisyphus, OpenCode agent orchestration, with parallel design consultation and implementation review.

**Any Additional AI Details you'd like to share:**

The implementation was designed with multiple read-only design tracks, manually integrated, formatted, linted, and tested. A follow-up review pass checked goal fit, QA execution, code quality, security, and missed context; the non-blocking findings from that review were addressed in follow-up commits.

**NOTE:**
When responding to reviewer questions, please respond yourself rather than copy/pasting reviewer comments into an AI and pasting back its answer. We want to discuss with you, not your AI :)

- [x] I am an AI Agent filling out this form (check box if true)

## Summary

This PR fixes startup-recovery behavior when an `on_launch` hook times out: instead of logging a warning and continuing, the system now treats the timeout as a real failure so affected instances are marked `Status::Error` with clear “what timed out” context. This prevents the misleading appearance of a healthy session after a broken or incomplete setup.

## What Changed

- **Typed timeout error added**
  - Introduced a structured `HookTimeout` error (captures the timed-out command and timeout duration) in `repo_config`.

- **Timeouts now propagate during recovery (but not other flows)**
  - During **sandboxed** launches, if the error chain includes `HookTimeout`, the hook timeout now returns `Err` (instead of warn-and-continue).
  - During **host** (non-sandboxed) launches, the command builders now distinguish timeout failures and propagate them as typed errors; non-timeout hook failures still log warnings and continue as before.

- **Recovery now stamps instance failure consistently**
  - `run_recovery_for_instance` centralizes translation of recovery errors into instance state:
    - sets `Status::Error`
    - records `last_error` / `last_error_check`
    - formats the timeout message as: `"on_launch hook timed out after Ns: <cmd>"`
  - Error classification is resilient to additional wrapping by scanning the full error chain.

- **Daemon cascade handling simplified**
  - The daemon recovery cascade completion no longer manually mutates instance error fields; it relies on the recovery helper to do that consistently.

- **Tests + documentation**
  - Added integration tests to verify:
    - timeout errors produce a `HookTimeout` chain with correct `cmd` and `timeout_secs`
    - non-timeout hook failures are not misclassified
  - Extended unit tests around recovery error formatting/classification.
  - Updated `repo-config.md` to clarify that recovery differs: timed-out `on_launch` hooks mark recovered sessions as errored instead of proceeding.

## Benefits

- Prevents instances from being left in a “healthy-looking” state after their startup hooks were killed.
- Provides operators with precise, user-facing timeout details (which command, and for how long).
- Ensures consistent error handling across recovery workers (daemon and TUI) while keeping non-recovery behavior unchanged.

### CODE REVIEW

**Review by njbrake — APPROVED** [review]
_Note: this review was drafted by Claude via back-and-forth with @njbrake. The reasoning and decisions are his; the prose is Claude's._

Approving. This is a precise, well-scoped fix for #1889.

I traced the full cascade: `build_host_command` / `build_launch_command` propagate `Err` via `?` through `start_with_size_opts` -> `start_with_resume_fallback` -> `restart_with_size_opts` -> `run_recovery_for_instance`. The hook runs at Tier-1, so on timeout the `Err` returns before any tmux session is created; no degraded session launches and Tier-2 is never reached.

Two things I specifically verified:

- The production invariant holds. `HookTimeoutScope::for_recovery()` is the only production scope installer, `current_hook_timeout()` returns `Some` only under an active scope, and `run_hook_with_timeout` is the sole `HookTimeout` producer. So `HookTimeout` is genuinely unconstructable off the recovery path, as the docstrings claim.
- The container-path detection is live, not dead code. `execute_hooks_in_container` routes through the same `run_hooks_captured` as the host path, so a sandboxed recovery whose container `on_launch` hook hangs does produce `HookTimeout`.

Nice side effect: centralizing the stamping in `run_recovery_for_instance` also fixes the TUI path, which on main only stamped `Status::Error` for the worker-panic branch and not the cascade-`Err` branch. No double-stamping, since the panic branches still stamp manually.

One non-blocking note: AC #6 of the issue asked for a literal end-to-end cascade test (`on_launch = ["sleep 60"]`, assert post-cascade `Status::Error`). You decomposed it into `stamp_recovery_error` + `format_recovery_last_error` unit tests plus integration tests proving `execute_hooks` yields a `HookTimeout` in the chain. That is a reasonable trade given how expensive and flaky a real tmux + hung-hook cascade test would be; the only untested seam is the 4-line glue wiring `run_recovery_for_instance` to `stamp_recovery_error` on `Err`. Worth a sentence in the PR noting the decomposition was intentional.
